# Generated by Django 4.2.21 on 2025-06-08 15:24

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=files.models.file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('reference_count', models.IntegerField(default=1)),
                ('original_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='files.file')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['file_hash'], name='files_file_file_ha_868749_idx'), models.Index(fields=['file_type'], name='files_file_file_ty_2d7e73_idx'), models.Index(fields=['uploaded_at'], name='files_file_uploade_726d10_idx'), models.Index(fields=['size'], name='files_file_size_6009e9_idx')],
            },
        ),
    ]
